// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopApp.Context;

namespace ShopApp.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20191216052744_Fix4")]
    partial class Fix4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ShopApp.Models.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Baskets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0342da95-ff87-47a7-a906-9cf5434f193f"),
                            HasPaid = false
                        });
                });

            modelBuilder.Entity("ShopApp.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BasketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f00cac80-ff35-40a2-a773-083f36b6e6df"),
                            Cost = 1000,
                            Description = "Белая корова",
                            Name = "Корова"
                        },
                        new
                        {
                            Id = new Guid("036fa4fd-1f52-4b2d-815f-b6f5f28f8dd0"),
                            Cost = 100,
                            Description = "Белый хлеб",
                            Name = "Хлеб"
                        },
                        new
                        {
                            Id = new Guid("88e6106d-77d4-4e4e-8bdc-f66b8974ce1e"),
                            Cost = 250,
                            Description = "Коровье",
                            Name = "Молоко"
                        });
                });

            modelBuilder.Entity("ShopApp.Models.Product", b =>
                {
                    b.HasOne("ShopApp.Models.Basket", null)
                        .WithMany("Products")
                        .HasForeignKey("BasketId");
                });
#pragma warning restore 612, 618
        }
    }
}
