// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopApp.Context;

namespace ShopApp.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20191215181654_Fix")]
    partial class Fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ShopApp.Models.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Baskets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77408561-2fb3-43fe-8147-e5ca7ad020e9"),
                            HasPaid = false
                        });
                });

            modelBuilder.Entity("ShopApp.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BasketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba8bce03-7ddd-4d5e-934e-064a6ea1a6ec"),
                            Cost = 1000,
                            Description = "Белая корова",
                            Name = "Корова"
                        },
                        new
                        {
                            Id = new Guid("c62eaf90-ad58-4c40-9e64-bc3cb93a6da1"),
                            Cost = 100,
                            Description = "Белый хлеб",
                            Name = "Хлеб"
                        },
                        new
                        {
                            Id = new Guid("208f1acd-499e-4e97-bd54-bfc1161b7f2d"),
                            Cost = 250,
                            Description = "Коровье",
                            Name = "Молоко"
                        });
                });

            modelBuilder.Entity("ShopApp.Models.Product", b =>
                {
                    b.HasOne("ShopApp.Models.Basket", "Basket")
                        .WithMany("Products")
                        .HasForeignKey("BasketId");
                });
#pragma warning restore 612, 618
        }
    }
}
