// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopApp.Context;

namespace ShopApp.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20191216050809_Fix3")]
    partial class Fix3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ShopApp.Models.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Baskets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0dac153d-d1d0-4fa2-8877-c268f472f28b"),
                            HasPaid = false
                        });
                });

            modelBuilder.Entity("ShopApp.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BasketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5b2df4f-5144-426f-a96f-639bc93dbc13"),
                            Cost = 1000,
                            Description = "Белая корова",
                            Name = "Корова"
                        },
                        new
                        {
                            Id = new Guid("446d3b8f-7589-4790-b65f-f4e9b0ce749e"),
                            Cost = 100,
                            Description = "Белый хлеб",
                            Name = "Хлеб"
                        },
                        new
                        {
                            Id = new Guid("caca4e74-5667-44e0-9e69-d255ed66fd2a"),
                            Cost = 250,
                            Description = "Коровье",
                            Name = "Молоко"
                        });
                });

            modelBuilder.Entity("ShopApp.Models.Product", b =>
                {
                    b.HasOne("ShopApp.Models.Basket", null)
                        .WithMany("Products")
                        .HasForeignKey("BasketId");
                });
#pragma warning restore 612, 618
        }
    }
}
